<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4H738JD" failures="3" tests="8" name="runner.TestRunner" time="10.441" errors="0" timestamp="2024-07-14T13:34:43 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="0.014"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.005"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.050">
    <failure message="expected [15] but found [20]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [15] but found [20]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at pages.Cucumber_BDD_Actions.verifySumViaHardAssert(Cucumber_BDD_Actions.java:39)
at com.qa.mystepdefs.Cucumber_BDD_StepDef.I_verify_sum_via_hard_assert(Cucumber_BDD_StepDef.java:38)
at ✽.I verify sum of 5 with 10 is 20 via hard assert(file:///D:/Selenium_Cucumber_TestNG_API_Framework/src/test/resources/features/Cucumber_BDD.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="0.004"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.009">
    <failure message="expected [4] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [4] but found [2]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at pages.Cucumber_BDD_Actions.verifySumViaHardAssert(Cucumber_BDD_Actions.java:39)
at com.qa.mystepdefs.Cucumber_BDD_StepDef.I_verify_sum_via_hard_assert(Cucumber_BDD_StepDef.java:38)
at ✽.I verify sum of 2 with 2 is 2 via hard assert(file:///D:/Selenium_Cucumber_TestNG_API_Framework/src/test/resources/features/Cucumber_BDD.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="10.347"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.004"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.008">
    <failure message="expected [8] but found [6]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8] but found [6]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at pages.Cucumber_BDD_Actions.verifySumViaHardAssert(Cucumber_BDD_Actions.java:39)
at com.qa.mystepdefs.Cucumber_BDD_StepDef.I_verify_sum_via_hard_assert(Cucumber_BDD_StepDef.java:38)
at ✽.I verify sum of 4 with 4 is 6 via hard assert(file:///D:/Selenium_Cucumber_TestNG_API_Framework/src/test/resources/features/Cucumber_BDD.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
